# KPI: Product View Rate
# Generated: 2025-12-08T05:18:12.061Z
# Contributed by: devyendar-maganti


KPI Name: Product View Rate



















Status: draft

Contributed By: devyendar-maganti

Created At: 2025-12-08T05:18:11.241+00:00



